import { type PendingRequest } from './types';

export const MOCK_PENDING_REQUESTS: PendingRequest[] = [
  {
    id: 'req-1',
    operatorName: 'Juan Pérez',
    processId: '1',
    processName: 'Q120 — 1 Polo',
    operationId: 'op-2',
    operationName: 'Soldar contacto inferior',
    tiempoEstandarSeg: 18,
    requestDate: '2026-04-20T08:00:00Z',
    attemptNumber: 3,
    maxAttempts: 4,
    status: 'available',
  },
  {
    id: 'req-2',
    operatorName: 'María García',
    processId: '1',
    processName: 'Q120 — 1 Polo',
    operationId: 'op-3',
    operationName: 'Insertar resorte de contacto',
    tiempoEstandarSeg: 12,
    requestDate: '2026-04-21T09:30:00Z',
    attemptNumber: 1,
    maxAttempts: 4,
    status: 'available',
  },
  {
    id: 'req-3',
    operatorName: 'Roberto Silva',
    processId: '6',
    processName: 'Q150 — 4 Polos',
    operationId: 'op-12',
    operationName: 'Insertar bimetálico',
    tiempoEstandarSeg: 25,
    requestDate: '2026-04-19T14:00:00Z',
    attemptNumber: 2,
    maxAttempts: 4,
    status: 'cooldown',
    cooldownUntil: '2026-04-27T14:00:00Z',
  },
  {
    id: 'req-4',
    operatorName: 'Ana Torres',
    processId: '2',
    processName: 'Q120 L2 — 1 Polo',
    operationId: 'op-7',
    operationName: 'Soldar contacto inferior L2',
    tiempoEstandarSeg: 20,
    requestDate: '2026-04-22T11:00:00Z',
    attemptNumber: 1,
    maxAttempts: 4,
    status: 'available',
  },
];
