import { type OroEvaluationRecord, type PendingRequest } from './types';

export const MOCK_PENDING_REQUESTS: PendingRequest[] = [
  {
    id: 'req-1',
    operatorName: 'Juan Pérez',
    processId: '1',
    processName: 'Q120 — 1 Polo',
    operationId: 'op-2',
    operationName: 'Soldar contacto inferior',
    tiempoEstandarSeg: 18,
    requestDate: '2026-04-20T08:00:00Z',
    attemptNumber: 3,
    maxAttempts: 4,
    status: 'available',
  },
  {
    id: 'req-2',
    operatorName: 'María García',
    processId: '1',
    processName: 'Q120 — 1 Polo',
    operationId: 'op-3',
    operationName: 'Insertar resorte de contacto',
    tiempoEstandarSeg: 12,
    requestDate: '2026-04-21T09:30:00Z',
    attemptNumber: 1,
    maxAttempts: 4,
    status: 'available',
  },
  {
    id: 'req-3',
    operatorName: 'Roberto Silva',
    processId: '6',
    processName: 'Q150 — 4 Polos',
    operationId: 'op-12',
    operationName: 'Insertar bimetálico',
    tiempoEstandarSeg: 25,
    requestDate: '2026-04-19T14:00:00Z',
    attemptNumber: 2,
    maxAttempts: 4,
    status: 'cooldown',
    cooldownUntil: '2026-04-27T14:00:00Z',
  },
  {
    id: 'req-4',
    operatorName: 'Ana Torres',
    processId: '2',
    processName: 'Q120 L2 — 1 Polo',
    operationId: 'op-7',
    operationName: 'Soldar contacto inferior L2',
    tiempoEstandarSeg: 20,
    requestDate: '2026-04-22T11:00:00Z',
    attemptNumber: 1,
    maxAttempts: 4,
    status: 'available',
  },
];

export const MOCK_ORO_EVALUATIONS: OroEvaluationRecord[] = [
  {
    id: 'eval-1',
    operatorName: 'Carlos Mendoza',
    processName: 'Q120 — 1 Polo',
    operationName: 'Colocar tapa superior',
    evaluatedAt: '2026-04-18T10:30:00Z',
    tiempoRegistradoSeg: 15.4,
    tiempoEstandarSeg: 14,
    attemptNumber: 1,
    result: 'failed',
  },
  {
    id: 'eval-2',
    operatorName: 'Laura Romero',
    processName: 'Q120 L2 — 1 Polo',
    operationName: 'Soldar contacto inferior L2',
    evaluatedAt: '2026-04-19T14:00:00Z',
    tiempoRegistradoSeg: 18.2,
    tiempoEstandarSeg: 20,
    attemptNumber: 2,
    result: 'passed',
  },
  {
    id: 'eval-3',
    operatorName: 'Juan Pérez',
    processName: 'Q120 — 1 Polo',
    operationName: 'Soldar contacto inferior',
    evaluatedAt: '2026-04-20T09:15:00Z',
    tiempoRegistradoSeg: 17.8,
    tiempoEstandarSeg: 18,
    attemptNumber: 2,
    result: 'passed',
  },
  {
    id: 'eval-4',
    operatorName: 'Roberto Silva',
    processName: 'Q150 — 4 Polos',
    operationName: 'Insertar bimetálico',
    evaluatedAt: '2026-04-21T11:45:00Z',
    tiempoRegistradoSeg: 29.6,
    tiempoEstandarSeg: 25,
    attemptNumber: 1,
    result: 'failed',
  },
  {
    id: 'eval-5',
    operatorName: 'María García',
    processName: 'Q120 — 1 Polo',
    operationName: 'Insertar resorte de contacto',
    evaluatedAt: '2026-04-22T08:00:00Z',
    tiempoRegistradoSeg: 11.3,
    tiempoEstandarSeg: 12,
    attemptNumber: 1,
    result: 'passed',
  },
  {
    id: 'eval-6',
    operatorName: 'Ana Torres',
    processName: 'Q120 L2 — 1 Polo',
    operationName: 'Soldar contacto inferior L2',
    evaluatedAt: '2026-04-23T07:30:00Z',
    tiempoRegistradoSeg: 19.1,
    tiempoEstandarSeg: 20,
    attemptNumber: 1,
    result: 'passed',
  },
];
