import { type PendingOperator, type ProcessLineStats } from './types';

export const MOCK_LINE_STATS: ProcessLineStats[] = [
  {
    processId: '1',
    processName: 'Q120 — 1 Polo',
    totalOperators: 6,
    certified: 4,
    inProgress: 1,
    uncertified: 1,
    risk: 'ok',
  },
  {
    processId: '2',
    processName: 'Q120 L2 — 1 Polo',
    totalOperators: 4,
    certified: 1,
    inProgress: 1,
    uncertified: 2,
    risk: 'warning',
  },
  {
    processId: '6',
    processName: 'Q150 — 4 Polos',
    totalOperators: 3,
    certified: 1,
    inProgress: 1,
    uncertified: 1,
    risk: 'warning',
  },
  {
    processId: '9',
    processName: 'Q180 — 2 Polos L2',
    totalOperators: 3,
    certified: 2,
    inProgress: 1,
    uncertified: 0,
    risk: 'ok',
  },
];

export const MOCK_PENDING_OPERATORS: PendingOperator[] = [
  {
    operatorId: 'op-carlos',
    operatorName: 'Carlos Mendoza',
    operationName: 'Insertar contacto inferior',
    processName: 'Q120 — 1 Polo',
    attemptNumber: 0,
    maxAttempts: 4,
  },
  {
    operatorId: 'op-roberto',
    operatorName: 'Roberto Silva',
    operationName: 'Insertar contacto inferior',
    processName: 'Q120 — 1 Polo',
    attemptNumber: 1,
    maxAttempts: 4,
    lastAttemptDate: '2026-04-10T09:00:00Z',
  },
  {
    operatorId: 'op-juan',
    operatorName: 'Juan Pérez',
    operationName: 'Soldar contacto inferior',
    processName: 'Q120 — 1 Polo',
    attemptNumber: 2,
    maxAttempts: 4,
    lastAttemptDate: '2026-04-20T09:00:00Z',
  },
  {
    operatorId: 'op-ana',
    operatorName: 'Ana Torres',
    operationName: 'Insertar resorte',
    processName: 'Q120 — 1 Polo',
    attemptNumber: 1,
    maxAttempts: 4,
    lastAttemptDate: '2026-04-19T14:00:00Z',
  },
  {
    operatorId: 'op-carlos-2',
    operatorName: 'Carlos Mendoza',
    operationName: 'Insertar contacto L2',
    processName: 'Q120 L2 — 1 Polo',
    attemptNumber: 1,
    maxAttempts: 4,
    lastAttemptDate: '2026-04-15T10:00:00Z',
  },
  {
    operatorId: 'op-roberto-6',
    operatorName: 'Roberto Silva',
    operationName: 'Insertar bimetálico',
    processName: 'Q150 — 4 Polos',
    attemptNumber: 1,
    maxAttempts: 4,
    lastAttemptDate: '2026-04-21T11:45:00Z',
  },
];
