import {
  type EmployeeDrillData,
  type PendingOperator,
  type ProcessLineStats,
} from './types';

export const MOCK_LINE_STATS: ProcessLineStats[] = [
  {
    processId: '1',
    processName: 'Q120 — 1 Polo',
    totalOperators: 6,
    certified: 4,
    inProgress: 1,
    uncertified: 1,
    risk: 'ok',
  },
  {
    processId: '2',
    processName: 'Q120 L2 — 1 Polo',
    totalOperators: 4,
    certified: 1,
    inProgress: 1,
    uncertified: 2,
    risk: 'warning',
  },
  {
    processId: '6',
    processName: 'Q150 — 4 Polos',
    totalOperators: 3,
    certified: 1,
    inProgress: 1,
    uncertified: 1,
    risk: 'warning',
  },
  {
    processId: '9',
    processName: 'Q180 — 2 Polos L2',
    totalOperators: 3,
    certified: 2,
    inProgress: 1,
    uncertified: 0,
    risk: 'ok',
  },
];

export const MOCK_PENDING_OPERATORS: PendingOperator[] = [
  {
    operatorId: 'op-carlos',
    operatorName: 'Carlos Mendoza',
    operationName: 'Insertar contacto inferior',
    processName: 'Q120 — 1 Polo',
    attemptNumber: 0,
    maxAttempts: 4,
  },
  {
    operatorId: 'op-roberto',
    operatorName: 'Roberto Silva',
    operationName: 'Insertar contacto inferior',
    processName: 'Q120 — 1 Polo',
    attemptNumber: 1,
    maxAttempts: 4,
    lastAttemptDate: '2026-04-10T09:00:00Z',
  },
  {
    operatorId: 'op-juan',
    operatorName: 'Juan Pérez',
    operationName: 'Soldar contacto inferior',
    processName: 'Q120 — 1 Polo',
    attemptNumber: 2,
    maxAttempts: 4,
    lastAttemptDate: '2026-04-20T09:00:00Z',
  },
  {
    operatorId: 'op-ana',
    operatorName: 'Ana Torres',
    operationName: 'Insertar resorte',
    processName: 'Q120 — 1 Polo',
    attemptNumber: 1,
    maxAttempts: 4,
    lastAttemptDate: '2026-04-19T14:00:00Z',
  },
  {
    operatorId: 'op-carlos-2',
    operatorName: 'Carlos Mendoza',
    operationName: 'Insertar contacto L2',
    processName: 'Q120 L2 — 1 Polo',
    attemptNumber: 1,
    maxAttempts: 4,
    lastAttemptDate: '2026-04-15T10:00:00Z',
  },
  {
    operatorId: 'op-roberto-6',
    operatorName: 'Roberto Silva',
    operationName: 'Insertar bimetálico',
    processName: 'Q150 — 4 Polos',
    attemptNumber: 1,
    maxAttempts: 4,
    lastAttemptDate: '2026-04-21T11:45:00Z',
  },
];

export const MOCK_EMPLOYEE_DRILL: Record<string, EmployeeDrillData> = {
  'op-juan': {
    operatorId: 'op-juan',
    operatorName: 'Juan Pérez',
    attempts: [
      {
        id: 'att-juan-1',
        operationName: 'Insertar contacto inferior',
        processName: 'Q120 — 1 Polo',
        evaluatorName: 'Carlos Méndez',
        attemptNumber: 1,
        completedAt: '2026-01-15T10:30:00Z',
        tiempoRegistradoSeg: 13,
        tiempoEstandarSeg: 15,
        result: 'passed',
      },
      {
        id: 'att-juan-2',
        operationName: 'Soldar contacto inferior',
        processName: 'Q120 — 1 Polo',
        evaluatorName: 'Laura Ríos',
        attemptNumber: 1,
        completedAt: '2026-02-18T09:00:00Z',
        tiempoRegistradoSeg: 20,
        tiempoEstandarSeg: 18,
        result: 'failed',
      },
      {
        id: 'att-juan-3',
        operationName: 'Soldar contacto inferior',
        processName: 'Q120 — 1 Polo',
        evaluatorName: 'Carlos Méndez',
        attemptNumber: 2,
        completedAt: '2026-04-20T09:15:00Z',
        tiempoRegistradoSeg: 17.8,
        tiempoEstandarSeg: 18,
        result: 'passed',
      },
      {
        id: 'att-juan-4',
        operationName: 'Insertar contacto L2',
        processName: 'Q180 — 2 Polos L2',
        evaluatorName: 'Laura Ríos',
        attemptNumber: 1,
        completedAt: '2026-04-05T12:00:00Z',
        tiempoRegistradoSeg: 11,
        tiempoEstandarSeg: 12,
        result: 'passed',
      },
    ],
  },
  'op-roberto': {
    operatorId: 'op-roberto',
    operatorName: 'Roberto Silva',
    attempts: [
      {
        id: 'att-roberto-1',
        operationName: 'Insertar contacto inferior',
        processName: 'Q120 — 1 Polo',
        evaluatorName: 'Carlos Méndez',
        attemptNumber: 1,
        completedAt: '2026-04-10T09:00:00Z',
        tiempoRegistradoSeg: 18.5,
        tiempoEstandarSeg: 15,
        result: 'failed',
      },
      {
        id: 'att-roberto-2',
        operationName: 'Montaje arco eléctrico',
        processName: 'Q150 — 4 Polos',
        evaluatorName: 'Carlos Méndez',
        attemptNumber: 1,
        completedAt: '2026-03-15T10:00:00Z',
        tiempoRegistradoSeg: 27,
        tiempoEstandarSeg: 30,
        result: 'passed',
      },
      {
        id: 'att-roberto-3',
        operationName: 'Insertar bimetálico',
        processName: 'Q150 — 4 Polos',
        evaluatorName: 'Carlos Méndez',
        attemptNumber: 1,
        completedAt: '2026-04-21T11:45:00Z',
        tiempoRegistradoSeg: 29.6,
        tiempoEstandarSeg: 25,
        result: 'failed',
      },
    ],
  },
  'op-carlos': {
    operatorId: 'op-carlos',
    operatorName: 'Carlos Mendoza',
    attempts: [
      {
        id: 'att-carlos-1',
        operationName: 'Insertar contacto L2',
        processName: 'Q120 L2 — 1 Polo',
        evaluatorName: 'Laura Ríos',
        attemptNumber: 1,
        completedAt: '2026-04-15T10:00:00Z',
        tiempoRegistradoSeg: 24,
        tiempoEstandarSeg: 20,
        result: 'failed',
      },
      {
        id: 'att-carlos-2',
        operationName: 'Insertar bimetálico',
        processName: 'Q150 — 4 Polos',
        evaluatorName: 'Laura Ríos',
        attemptNumber: 1,
        completedAt: '2026-04-08T14:00:00Z',
        tiempoRegistradoSeg: 30,
        tiempoEstandarSeg: 25,
        result: 'failed',
      },
    ],
  },
  'op-ana': {
    operatorId: 'op-ana',
    operatorName: 'Ana Torres',
    attempts: [
      {
        id: 'att-ana-1',
        operationName: 'Insertar contacto inferior',
        processName: 'Q120 — 1 Polo',
        evaluatorName: 'Carlos Méndez',
        attemptNumber: 1,
        completedAt: '2026-03-10T09:00:00Z',
        tiempoRegistradoSeg: 14,
        tiempoEstandarSeg: 15,
        result: 'passed',
      },
      {
        id: 'att-ana-2',
        operationName: 'Soldar contacto inferior',
        processName: 'Q120 — 1 Polo',
        evaluatorName: 'Carlos Méndez',
        attemptNumber: 1,
        completedAt: '2026-03-20T10:00:00Z',
        tiempoRegistradoSeg: 17,
        tiempoEstandarSeg: 18,
        result: 'passed',
      },
      {
        id: 'att-ana-3',
        operationName: 'Insertar resorte',
        processName: 'Q120 — 1 Polo',
        evaluatorName: 'Laura Ríos',
        attemptNumber: 1,
        completedAt: '2026-04-19T14:00:00Z',
        tiempoRegistradoSeg: 15.4,
        tiempoEstandarSeg: 12,
        result: 'failed',
      },
      {
        id: 'att-ana-4',
        operationName: 'Colocar cubierta superior',
        processName: 'Q120 — 1 Polo',
        evaluatorName: 'Carlos Méndez',
        attemptNumber: 1,
        completedAt: '2026-04-12T11:00:00Z',
        tiempoRegistradoSeg: 13,
        tiempoEstandarSeg: 14,
        result: 'passed',
      },
      {
        id: 'att-ana-5',
        operationName: 'Insertar contacto L2',
        processName: 'Q120 L2 — 1 Polo',
        evaluatorName: 'Laura Ríos',
        attemptNumber: 1,
        completedAt: '2026-04-22T08:00:00Z',
        tiempoRegistradoSeg: 19.1,
        tiempoEstandarSeg: 20,
        result: 'passed',
      },
    ],
  },
};
