import { type PillsProps } from '@material-hu/components/design-system/Pills/types';

import {
  type CertificationOperation,
  type CertificationProcess,
  type ProcessStatus,
} from './types';

export const STATUS_CONFIG: Record<
  ProcessStatus,
  { label: string; type: PillsProps['type'] }
> = {
  draft: { label: 'BORRADOR', type: 'neutral' },
  published: { label: 'PUBLICADO', type: 'success' },
  archived: { label: 'ARCHIVADO', type: 'disabled' },
};

export const STATUS_FILTER_OPTIONS = [
  { value: 'draft', label: 'Borrador' },
  { value: 'published', label: 'Publicado' },
  { value: 'archived', label: 'Archivado' },
];

export const MOCK_PROCESSES: CertificationProcess[] = [
  {
    id: '1',
    nombre: 'Q120 — 1 Polo',
    modelo: 'Q120',
    familia: 'Polo',
    linea: 'Línea 1',
    turno: 'Mañana',
    version: 1,
    status: 'published',
    createdAt: '2026-01-10T09:00:00Z',
  },
  {
    id: '2',
    nombre: 'Q120 L2 — 1 Polo',
    modelo: 'Q120 L2',
    familia: 'Polo',
    linea: 'Línea 2',
    turno: 'Tarde',
    version: 1,
    status: 'published',
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: '3',
    nombre: 'Q120 Bajo Volumen',
    modelo: 'Q120',
    familia: 'BV',
    linea: 'Línea 1',
    turno: 'Noche',
    version: 2,
    status: 'draft',
    createdAt: '2026-02-01T14:00:00Z',
  },
  {
    id: '4',
    nombre: 'Q130 — 2 Polos',
    modelo: 'Q130',
    familia: 'Polo',
    linea: 'Línea 3',
    turno: 'Mañana',
    version: 1,
    status: 'archived',
    createdAt: '2025-12-01T08:00:00Z',
  },
  {
    id: '5',
    nombre: 'Q140 — 3 Polos',
    modelo: 'Q140',
    familia: 'Polo',
    linea: 'Línea 1',
    turno: 'Tarde',
    version: 1,
    status: 'draft',
    createdAt: '2026-03-05T11:00:00Z',
  },
  {
    id: '6',
    nombre: 'Q150 — 4 Polos',
    modelo: 'Q150',
    familia: 'Polo',
    linea: 'Línea 2',
    turno: 'Mañana',
    version: 1,
    status: 'published',
    createdAt: '2026-03-20T08:00:00Z',
  },
  {
    id: '7',
    nombre: 'Q160 Bajo Volumen',
    modelo: 'Q160',
    familia: 'BV',
    linea: 'Línea 3',
    turno: 'Noche',
    version: 1,
    status: 'draft',
    createdAt: '2026-04-01T09:00:00Z',
  },
  {
    id: '8',
    nombre: 'Q170 — 1 Polo',
    modelo: 'Q170',
    familia: 'Polo',
    linea: 'Línea 1',
    turno: 'Tarde',
    version: 1,
    status: 'archived',
    createdAt: '2025-11-15T10:00:00Z',
  },
  {
    id: '9',
    nombre: 'Q180 — 2 Polos L2',
    modelo: 'Q180',
    familia: 'Polo',
    linea: 'Línea 2',
    turno: 'Mañana',
    version: 3,
    status: 'published',
    createdAt: '2026-02-20T11:00:00Z',
  },
  {
    id: '10',
    nombre: 'Q190 Alta Velocidad',
    modelo: 'Q190',
    familia: 'AV',
    linea: 'Línea 3',
    turno: 'Noche',
    version: 1,
    status: 'draft',
    createdAt: '2026-04-10T14:00:00Z',
  },
  {
    id: '11',
    nombre: 'Q200 — 1 Polo',
    modelo: 'Q200',
    familia: 'Polo',
    linea: 'Línea 1',
    turno: 'Mañana',
    version: 2,
    status: 'published',
    createdAt: '2026-01-25T09:00:00Z',
  },
  {
    id: '12',
    nombre: 'Q210 L2 — Bajo Volumen',
    modelo: 'Q210',
    familia: 'BV',
    linea: 'Línea 2',
    turno: 'Tarde',
    version: 1,
    status: 'archived',
    createdAt: '2025-10-30T08:00:00Z',
  },
];

export const MOCK_OPERATIONS: CertificationOperation[] = [
  {
    id: 'op-1',
    process_id: '1',
    orden: 1,
    nombre: 'Insertar contacto inferior',
    tiempo_estandar_seg: 12,
  },
  {
    id: 'op-2',
    process_id: '1',
    orden: 2,
    nombre: 'Soldar contacto inferior',
    tiempo_estandar_seg: 18,
  },
  {
    id: 'op-3',
    process_id: '1',
    orden: 3,
    nombre: 'Insertar resorte de contacto',
    tiempo_estandar_seg: 10,
  },
  {
    id: 'op-4',
    process_id: '1',
    orden: 4,
    nombre: 'Colocar cubierta superior',
    tiempo_estandar_seg: 8,
  },
  {
    id: 'op-5',
    process_id: '1',
    orden: 5,
    nombre: 'Verificar continuidad eléctrica',
    tiempo_estandar_seg: 15,
  },
  {
    id: 'op-6',
    process_id: '2',
    orden: 1,
    nombre: 'Insertar contacto inferior L2',
    tiempo_estandar_seg: 13,
  },
  {
    id: 'op-7',
    process_id: '2',
    orden: 2,
    nombre: 'Soldar contacto inferior L2',
    tiempo_estandar_seg: 20,
  },
  {
    id: 'op-8',
    process_id: '2',
    orden: 3,
    nombre: 'Colocar cubierta superior L2',
    tiempo_estandar_seg: 9,
  },
  {
    id: 'op-9',
    process_id: '3',
    orden: 1,
    nombre: 'Insertar contacto BV',
    tiempo_estandar_seg: 14,
  },
  {
    id: 'op-10',
    process_id: '3',
    orden: 2,
    nombre: 'Verificar aislamiento',
    tiempo_estandar_seg: 22,
  },
  {
    id: 'op-11',
    process_id: '6',
    orden: 1,
    nombre: 'Montaje de arco eléctrico',
    tiempo_estandar_seg: 30,
  },
  {
    id: 'op-12',
    process_id: '6',
    orden: 2,
    nombre: 'Insertar bimetálico',
    tiempo_estandar_seg: 16,
  },
  {
    id: 'op-13',
    process_id: '6',
    orden: 3,
    nombre: 'Calibrar disparador térmico',
    tiempo_estandar_seg: 45,
  },
];
